apiVersion: v1
kind: Service
metadata:
  name: fill-ai-service
spec:
  selector:
    app: fill-ai # Selects pods with the label app=nginx
  type: NodePort # Exposes the service on a static port on each Node's IP
  ports:
  - protocol: TCP
    port: 8080 # The port the service exposes
    targetPort: 8080 # The port the pods are running on
    nodePort: 30008 # The static port on the Node's IP (usually in range 30000-32767)
